export const PUSH_MESSAGE = "PUSH_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const CONNECTION_OPENED = "CONNECTION_OPENED";
export const CONNECTION_CLOSED = "CONNECTION_CLOSED";
